import type { ReadinessReport } from './types';

export interface SuggestedReadinessFile {
  path: string;
  readinessCategory: string;
  improves: string;
  whyUseful: string;
  content: string;
  alreadyInDeliveryPack: boolean;
}

const SUGGESTED_FILES: Omit<SuggestedReadinessFile, 'content' | 'alreadyInDeliveryPack'>[] = [
  {
    path: 'AGENTS.md',
    readinessCategory: 'AI agent instruction readiness',
    improves: 'Clear operating rules for coding agents.',
    whyUseful: 'Gives AI coding agents repository-specific boundaries, verification commands, and handoff rules.',
  },
  {
    path: 'CLAUDE.md',
    readinessCategory: 'AI agent instruction readiness',
    improves: 'Claude-specific execution guidance.',
    whyUseful: 'Helps Claude and similar agents work plan-first with clear safety and review expectations.',
  },
  {
    path: 'CONTRIBUTING.md',
    readinessCategory: 'Team workflow and governance',
    improves: 'Contributor workflow and review expectations.',
    whyUseful: 'Documents how humans and agents should validate changes before client handoff.',
  },
  {
    path: 'SECURITY.md',
    readinessCategory: 'Security and secret handling',
    improves: 'Security policy, disclosure path, and secret-handling boundaries.',
    whyUseful: 'Makes security expectations explicit before exposing repository context to AI tools.',
  },
  {
    path: 'docs/CRITICAL_FILES_POLICY.md',
    readinessCategory: 'Team workflow and governance / safety',
    improves: 'Human review rules for risky files.',
    whyUseful: 'Identifies files that should not be changed by agents without human approval.',
  },
  {
    path: 'docs/RELEASE_CHECKLIST.md',
    readinessCategory: 'Build, test and quality gates',
    improves: 'Repeatable release validation.',
    whyUseful: 'Turns test/build/export/report checks into a visible handoff gate.',
  },
  {
    path: 'docs/OWNERSHIP.md',
    readinessCategory: 'Team workflow and governance',
    improves: 'Ownership and review routing.',
    whyUseful: 'Shows who should review scanner, export, governance, and report changes.',
  },
  {
    path: '.github/workflows/ci.yml',
    readinessCategory: 'Build, test and quality gates',
    improves: 'Automated test and build verification.',
    whyUseful: 'Gives future scans a CI signal and gives agents a safe verification target.',
  },
];

export function buildSuggestedReadinessFixPack(report: ReadinessReport): SuggestedReadinessFile[] {
  const deliveryPackPaths = new Set([
    ...report.agentPack.map(file => file.name),
    ...report.mcpReadiness.generatedFiles.map(file => file.filename),
    '01-agent-instructions/AGENTS.md',
    '01-agent-instructions/CLAUDE.md',
    '04-testing/CI_QUALITY_GATE.yml',
    '06-client-handoff/CLIENT_HANDOFF_REPORT.md',
  ]);

  return SUGGESTED_FILES.map(file => ({
    ...file,
    alreadyInDeliveryPack: deliveryPackPaths.has(file.path) || deliveryPackPaths.has(file.path.split('/').pop() || file.path),
    content: buildSuggestedFileContent(report, file),
  }));
}

function buildSuggestedFileContent(report: ReadinessReport, file: Omit<SuggestedReadinessFile, 'content' | 'alreadyInDeliveryPack'>) {
  return [
    `# ${file.path}`,
    '',
    `Repository: ${report.repoName}`,
    `Generated by ShipSeal as a suggested readiness file.`,
    '',
    `## Readiness Category`,
    '',
    file.readinessCategory,
    '',
    `## Why This Helps`,
    '',
    file.whyUseful,
    '',
    `## What It Improves`,
    '',
    file.improves,
    '',
    `## Validation`,
    '',
    '- Run `npm run test` if available.',
    '- Run `npm run build` if available.',
    '- Review this file with the repository owner before committing it.',
    '',
    `## Safety Note`,
    '',
    'This suggested file does not write to GitHub automatically. Add it through a reviewed pull request.',
  ].join('\n');
}
