import { describe, expect, it } from 'vitest';
import { buildSampleReport } from '@/lib/readiness';
import { buildSuggestedReadinessFixPack } from '@/lib/readinessFixPack';

describe('Suggested Readiness Fix Pack generator', () => {
  it('maps suggested files to readiness categories with non-empty previews', () => {
    const pack = buildSuggestedReadinessFixPack(buildSampleReport());
    const paths = pack.map(file => file.path);

    expect(paths).toContain('AGENTS.md');
    expect(paths).toContain('CLAUDE.md');
    expect(paths).toContain('CONTRIBUTING.md');
    expect(paths).toContain('.github/workflows/ci.yml');
    expect(paths).toContain('docs/CRITICAL_FILES_POLICY.md');

    for (const file of pack) {
      expect(file.readinessCategory).toBeTruthy();
      expect(file.whyUseful).toBeTruthy();
      expect(file.improves).toBeTruthy();
      expect(file.content).toContain('Generated by ShipSeal');
    }
  });
});
