import type { ProjectIntake } from '../intake';

export interface ClientHandoffFiles {
  clientHandoffReport: string;
  executiveSummary: string;
  nextStepsRoadmap: string;
}

interface HandoffScoreSummary {
  repositoryName: string;
  score: string;
  status: string;
  isReady: boolean | null;
  criticalBlockers: Array<{ title?: string; detail?: string }>;
  improvements: Array<{ title?: string; category?: string; detail?: string }>;
  categories: Array<{ name?: string; earned?: number; max?: number }>;
  generatedFiles: string[];
  mcpStatus: string;
  mcpScore: string;
  aiActSummary: string;
}

const DISCLAIMER = 'Disclaimer: This is not legal advice and this is not a production security audit.';

export function generateClientHandoffFiles(intake: ProjectIntake, scoreJson?: unknown): ClientHandoffFiles {
  const summary = parseScoreSummary(scoreJson, intake.projectName);
  const strengths = topStrengths(summary);
  const risks = topRisks(summary, intake);
  const missingDocs = missingDocumentation(summary);
  const testing = testingStatus(summary);
  const goNoGo = goNoGoRecommendation(summary, intake);

  return {
    clientHandoffReport: renderClientHandoffReport(intake, summary, strengths, risks, missingDocs, testing, goNoGo),
    executiveSummary: renderExecutiveSummary(intake, summary, strengths, risks, goNoGo),
    nextStepsRoadmap: renderNextStepsRoadmap(intake, summary, risks, missingDocs),
  };
}

function renderClientHandoffReport(
  intake: ProjectIntake,
  summary: HandoffScoreSummary,
  strengths: string[],
  risks: string[],
  missingDocs: string[],
  testing: string,
  goNoGo: string
) {
  return [
    `# CLIENT_HANDOFF_REPORT.md - ${intake.projectName}`,
    '',
    'Generated by ShipSeal.',
    DISCLAIMER,
    '',
    '## Project overview',
    `- Project: ${intake.projectName}`,
    `- Client: ${valueOrNotProvided(intake.clientName)}`,
    `- Agency: ${valueOrNotProvided(intake.agencyName)}`,
    `- App description: ${valueOrNotProvided(intake.appDescription)}`,
    `- AI use case: ${valueOrNotProvided(intake.aiUseCase)}`,
    '',
    '## ShipSeal score summary',
    `- Repository: ${summary.repositoryName}`,
    `- Score: ${summary.score}`,
    `- Status: ${summary.status}`,
    `- Critical blockers: ${summary.criticalBlockers.length}`,
    '',
    '## Main strengths',
    ...asBullets(strengths),
    '',
    '## Main risks',
    ...asBullets(risks),
    '',
    '## Missing documentation',
    ...asBullets(missingDocs),
    '',
    '## Testing status',
    `- ${testing}`,
    '',
    '## AI Act readiness pre-screen',
    `- ${summary.aiActSummary}`,
    '',
    '## MCP readiness',
    `- MCP status: ${summary.mcpStatus}`,
    `- MCP score: ${summary.mcpScore}`,
    '',
    '## Go / No-Go recommendation',
    `- ${goNoGo}`,
    '',
    '## 30/60/90 day next steps roadmap',
    '### 30 days',
    '- Close critical blockers and confirm the Delivery Pack remains complete.',
    '- Confirm testing evidence for the main AI workflow and client-facing outputs.',
    '- Review AI Act, privacy, and transparency notes with the client owner.',
    '',
    '### 60 days',
    '- Add missing documentation and turn repeated manual checks into repeatable quality gates.',
    '- Improve monitoring, handoff notes, and MCP governance boundaries.',
    '- Re-run ShipSeal after remediation and compare score movement.',
    '',
    '### 90 days',
    '- Prepare a production hardening plan with security, privacy, legal, and operations owners.',
    '- Decide which optional improvements should become release standards.',
    '- Establish a recurring Delivery Pack refresh cadence.',
    '',
  ].join('\n');
}

function renderExecutiveSummary(
  intake: ProjectIntake,
  summary: HandoffScoreSummary,
  strengths: string[],
  risks: string[],
  goNoGo: string
) {
  return [
    `# EXECUTIVE_SUMMARY.md - ${intake.projectName}`,
    '',
    'Generated by ShipSeal.',
    DISCLAIMER,
    '',
    '## Summary',
    `${intake.projectName} was reviewed as an AI project delivery package. The current ShipSeal score is ${summary.score} with status ${summary.status}.`,
    '',
    '## Client context',
    `- Client: ${valueOrNotProvided(intake.clientName)}`,
    `- Agency: ${valueOrNotProvided(intake.agencyName)}`,
    `- AI use case: ${valueOrNotProvided(intake.aiUseCase)}`,
    '',
    '## What looks strong',
    ...asBullets(strengths.slice(0, 3)),
    '',
    '## What needs attention',
    ...asBullets(risks.slice(0, 3)),
    '',
    '## Go / No-Go recommendation',
    `- ${goNoGo}`,
    '',
  ].join('\n');
}

function renderNextStepsRoadmap(
  intake: ProjectIntake,
  summary: HandoffScoreSummary,
  risks: string[],
  missingDocs: string[]
) {
  return [
    `# NEXT_STEPS_ROADMAP.md - ${intake.projectName}`,
    '',
    'Generated by ShipSeal.',
    DISCLAIMER,
    '',
    '## Roadmap basis',
    `- ShipSeal score: ${summary.score}`,
    `- Status: ${summary.status}`,
    `- Main risk themes: ${risks.slice(0, 3).join('; ') || 'Not detected'}`,
    '',
    '## 30 days',
    '- Resolve all critical blockers or document why they are not applicable.',
    '- Review missing documentation: ' + (missingDocs.join('; ') || 'Not detected'),
    '- Run the testing pack eval cases and record pass/fail evidence.',
    '',
    '## 60 days',
    '- Convert recurring checks into CI or documented quality gates.',
    '- Confirm MCP access remains least-privilege and approval-gated.',
    '- Update client-facing transparency and privacy materials after reviewer feedback.',
    '',
    '## 90 days',
    '- Schedule a production security audit if the project is moving toward launch.',
    '- Re-run ShipSeal and compare score, blockers, and readiness changes.',
    '- Finalize client ownership for ongoing Delivery Pack maintenance.',
    '',
  ].join('\n');
}

function parseScoreSummary(scoreJson: unknown, fallbackRepositoryName: string): HandoffScoreSummary {
  const source = asRecord(scoreJson);
  const mcp = asRecord(source.mcpReadiness);
  const repoContext = asRecord(source.repoContextPack);

  return {
    repositoryName: stringValue(source.repositoryName) || fallbackRepositoryName || 'Not provided',
    score: typeof source.score === 'number' ? `${source.score}/100` : 'Not detected',
    status: stringValue(source.status) || 'Not detected',
    isReady: typeof source.isReady === 'boolean' ? source.isReady : null,
    criticalBlockers: arrayValue(source.criticalBlockers).map(asRecord),
    improvements: arrayValue(source.improvements).map(asRecord),
    categories: arrayValue(source.categories).map(asRecord),
    generatedFiles: arrayValue(source.generatedFiles).map(value => String(value)),
    mcpStatus: stringValue(mcp.status) || stringValue(repoContext.mcpStatus) || 'Not detected',
    mcpScore: typeof mcp.score === 'number' ? `${mcp.score}/100` : 'Not detected',
    aiActSummary: 'Pre-screen only. Review AI Act, transparency, privacy, and human oversight notes with qualified reviewers.',
  };
}

function topStrengths(summary: HandoffScoreSummary) {
  const strengths = summary.categories
    .filter(category => typeof category.earned === 'number' && typeof category.max === 'number' && category.max > 0 && category.earned / category.max >= 0.7)
    .slice(0, 4)
    .map(category => `${stringValue(category.name) || 'Readiness area'} is relatively strong (${category.earned}/${category.max}).`);

  if (summary.generatedFiles.length) strengths.push(`Delivery Pack generated ${summary.generatedFiles.length} core files.`);
  if (summary.isReady === true) strengths.push('No critical readiness blockers were reported by the scan.');

  return strengths.length ? strengths : ['Not detected'];
}

function topRisks(summary: HandoffScoreSummary, intake: ProjectIntake) {
  const risks = summary.criticalBlockers.slice(0, 5).map(blocker => `${stringValue(blocker.title) || 'Critical blocker'}: ${stringValue(blocker.detail) || 'Details not provided'}.`);

  if (summary.isReady === false && !risks.length) risks.push('The repository is not currently marked ready by the ShipSeal readiness rule.');
  if (intake.handlesPersonalData) risks.push('Personal data handling was indicated; privacy/GDPR review may be needed.');
  if (intake.usedInEU && intake.generatesUserFacingContent) risks.push('EU use with user-facing AI output was indicated; transparency notice review is recommended.');
  if (!intake.hasHumanApproval) risks.push('Human approval was not indicated; treat this as a delivery governance risk.');

  return risks.length ? risks : ['No major risks detected from available data.'];
}

function missingDocumentation(summary: HandoffScoreSummary) {
  const missing = summary.improvements
    .filter(improvement => /README|documentation|CONTRIBUTING|CODEOWNERS|Testing strategy|Deployment|Security/i.test(`${improvement.title || ''} ${improvement.category || ''}`))
    .slice(0, 6)
    .map(improvement => stringValue(improvement.title) || stringValue(improvement.category) || 'Documentation item');

  return missing.length ? missing : ['Not detected'];
}

function testingStatus(summary: HandoffScoreSummary) {
  const quality = summary.categories.find(category => /build|test|quality/i.test(stringValue(category.name) || ''));
  if (quality && typeof quality.earned === 'number' && typeof quality.max === 'number') {
    return `Testing and quality signal: ${quality.earned}/${quality.max}. Use the testing pack before client delivery.`;
  }
  return 'Not detected. Use the testing pack before client delivery.';
}

function goNoGoRecommendation(summary: HandoffScoreSummary, intake: ProjectIntake) {
  if (summary.criticalBlockers.length > 0) return 'No-Go for unsupervised delivery until critical blockers are resolved or formally accepted.';
  if (summary.isReady === true && intake.hasHumanApproval) return 'Go for controlled handoff with documented human approval and standard review.';
  if (summary.isReady === true) return 'Conditional Go for handoff; add human approval ownership before production use.';
  return 'Conditional Go for discovery or remediation only; not recommended for production handoff yet.';
}

function asBullets(values: string[]) {
  return values.length ? values.map(value => `- ${value}`) : ['- Not detected'];
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' ? value as Record<string, unknown> : {};
}

function arrayValue(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

function stringValue(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function valueOrNotProvided(value?: string) {
  return value?.trim() || 'Not provided';
}
